version: '3.4'

services:
  shadowsocks:
    restart: always
    build: .
    container_name: shadowsocks
    ports:
      - "443:443/tcp"
      - "443:443/udp"
    dns: 8.8.8.8
    command: -s "-s 0.0.0.0 -p 443 -k passgfw -m aes-256-cfb --fast-open -u"