version: '3'

services:
  shadowsocks:
    build: .
    container_name: shadowsocks
    ports:
      - '10001:10001'
    restart: always
    command: -m "ss-server" -s "-s 0.0.0.0 -p 10001 -k passgfw -m rc4-md5 -u"