version: '3.4'

services:
  shadowsocks:
    restart: always
    build: .
    container_name: shadowsocks
    ports:
      - "10001:10001/tcp"
      - "10001:10001/udp"
    dns: 8.8.8.8
    command: -s "-s 0.0.0.0 -p 10001 -k passgfw -m rc4-md5 --fast-open -u"